version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - ./output:/app/output
    environment:
      - NODE_ENV=production
    # Default command - can override with docker-compose run
    command: >
      node parallelArchiveScraperPlaywright.js
      --start "2024-01-01"
      --end "2024-01-07"
      --workers 2
      --headless
    # Increase shared memory for Chromium
    shm_size: '2gb'
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G